# Generated by Django 4.0.4 on 2022-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.CharField(default='service', max_length=200),
        ),
    ]
