# Generated by Django 4.0.4 on 2022-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_lastname', models.CharField(max_length=50)),
                ('patient_species', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('patient_weight', models.IntegerField()),
                ('color_color', models.CharField(max_length=50)),
            ],
        ),
    ]
