# Generated by Django 4.0.4 on 2022-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_patient_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='color_color',
            new_name='color',
        ),
    ]
