# Generated by Django 4.0.4 on 2022-05-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_color_color_patient_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='color',
            new_name='color_color',
        ),
    ]
