# Generated by Django 4.0.4 on 2022-05-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_patient_user_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.service'),
        ),
    ]
