# Generated by Django 4.0.4 on 2022-05-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_patient_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='services',
        ),
    ]
